### ISSUE TITLE
update to Condorcet.Vote web page

### ISSUE THREAD

**Issue by HightopRaven** [julien-boudry/Condorcet.Vote#5]
It appears that https://www.condorcet.vote/ is using v1.8x, and there remain numerous issues with use of the web page. Are there plans to update this web page with more recent code version from the https://github.com/julien-boudry/Condorcet/ repository? If I submit other new issues with the web page, is there interest and time available  to make revisions to the web page?

**Comment by julien-boudry** [comment]
Hi,

I'm always interested for comments. 

But condorcet.vote is more an extension of Condorcet PHP than a real project. A demonstration with a web interface. Indeed, I must to Update Condorcet PHP to 2.1, but it will not resolve the website bugs. You can also consider to use Condorcet PHP as a command line application. Probably I can help.

Maybee I can take some time for most urgent bugfix on Condorcet.Vote

**Comment by julien-boudry** [comment]
Done
